=== AlexandruNicolescu00/jolie-exercises/xml/degree.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified">

  <xs:element name="degree">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="course" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="course">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title" type="xs:string"/>
        <xs:element ref="professor" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="cfus" type="xs:positiveInteger"/>
      </xs:sequence>
  </xs:complexType>
  </xs:element>
  
  <xs:element name="professor">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="matriculaId" type="xs:ID"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

<!-- 
<xs:element name="degree" type="degreeType"/>

<xs:complexType name="degreeType">
  <xs:sequence>
    <xs:element ref="course" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>
 -->

=== AlexandruNicolescu00/jolie-exercises/xml/degree.xml
<?xml version="1.0" encoding="UTF-8"?>
<degree xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.w3schools.com degree.xsd">
  <course>
    <title>ARCHITETTURE SOFTWARE A MICROSERVIZI</title>
    <professor>
      <name>Davide Rossi</name>
      <matriculaId>a1</matriculaId>
    </professor>
    <professor>
      <name>Ivan Lanese</name>
      <matriculaId>a2</matriculaId>
    </professor>
    <cfus>6</cfus>
  </course>

  <course>
    <title>COMPLEX SYSTEMS AND NETWORK SCIENCE</title>
    <professor>
      <name>Ozalp Babaoglu</name>
      <matriculaId>a3</matriculaId>
    </professor>
    <cfus>6</cfus>
  </course>

  <course>
    <title>FONDAMENTI LOGICI DELL'INFORMATICA</title>
    <professor>
      <name>Luca Padovani</name>
      <matriculaId>a4</matriculaId>
    </professor>
    <professor>
      <name>Claudio Sacerdoti Coen</name>
      <matriculaId>a5</matriculaId>
    </professor>
    <cfus>6</cfus>
  </course>
</degree>
